version: 0.2
env:
  parameter-store:
    TELEGRAM_TOKEN: "/XlivePriceBot/token"
    API_GW: "/XlivePriceBot/base_url"
phases:
  build:
    commands:
      - curl -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/setWebhook?url=${API_GW}"
